# Android NDK project makefile autogenerated by Premake

# Preamble
DEPENDENCY_PATH := $(call my-dir)
LOCAL_PATH := $(abspath $(DEPENDENCY_PATH))

# Compile kernels using ispc
#$(shell ($(LOCAL_PATH)/ispc -O2 "$(LOCAL_PATH)/kernels.ispc" -o "$(LOCAL_PATH)/../obj/local/$(TARGET_ARCH_ABI)/kernels.o" -h "$(LOCAL_PATH)/kernels_ispc.h" --arch=x86 --target=avx --opt=fast-math))
#$(shell ($(LOCAL_PATH)/ispc -O2 "$(LOCAL_PATH)/kernels.ispc" --emit-c++ --target=generic-4 -o $(LOCAL_PATH)/../obj/local/$(TARGET_ARCH_ABI)/kernels.cpp))

include $(CLEAR_VARS)
# Project configuration
LOCAL_MODULE := MySample
LOCAL_CFLAGS := -DCPUT_FOR_OGLES3 -DCPUT_FOR_OGLES3_1 -DCPUT_FOR_OGLES -DCPUT_OS_ANDROID -DDEBUG -std=c++11
LOCAL_CPP_FEATURES := exceptions
LOCAL_LDLIBS := -llog -landroid -lEGL -lGLESv3
LOCAL_STATIC_LIBRARIES := CPUT-prebuilt android_native_app_glue

# Include paths
LOCAL_C_INCLUDES := Media/building/Shader

# Source files
#VisualGDBAndroid: AutoUpdateSourcesInNextLine
LOCAL_SRC_FILES := ClusteredShadingSample.cpp ColorUtil.cpp FragmentFactory.cpp GLProgram.cpp LightGrid.cpp main.cpp

# Build instructions
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
# Declare pre-built CPUT library
LOCAL_MODULE := CPUT-prebuilt
CPUT_PATH := $(LOCAL_PATH)/../CPUT
LOCAL_SRC_FILES := $(CPUT_PATH)/obj/local/$(TARGET_ARCH_ABI)/libCPUT.a

# The LOCAL_EXPORT_C_INCLUDES definition ensures that any module that depends on the 
# prebuilt one will have its LOCAL_C_INCLUDES automatically prepended with the path to the 
# prebuilt's include directory, and will thus be able to find headers inside that.
LOCAL_EXPORT_C_INCLUDES := $(CPUT_PATH)/CPUT $(CPUT_PATH)/middleware/glew-1.10.0/include $(CPUT_PATH)/middleware

include $(PREBUILT_STATIC_LIBRARY)

$(call import-module, android/native_app_glue)
