# Android NDK application makefile autogenerated by Premake
PROJECT_PATH := .

# Application settings
APP_PLATFORM := android-18
APP_ABI := x86 armeabi-v7a
APP_STL := stlport_static
APP_OPTIM := debug

