# Android NDK project makefile autogenerated by Premake

# Preamble
DEPENDENCY_PATH := $(call my-dir)
LOCAL_PATH := $(abspath $(DEPENDENCY_PATH))
include $(CLEAR_VARS)

# Project configuration
LOCAL_MODULE := CPUT
LOCAL_CFLAGS :=-DCPUT_FOR_OGLES3 -DCPUT_FOR_OGLES3_1 -DCPUT_FOR_OGLES -DCPUT_OS_ANDROID -DDEBUG -DKTX_OPENGL_ES3=1 -DSUPPORT_SOFTWARE_ETC_UNPACK=0 -std=c++11
LOCAL_CPP_FEATURES := exceptions
LOCAL_STATIC_LIBRARIES += android_native_app_glue

# Include paths
LOCAL_C_INCLUDES := $(LOCAL_PATH)/../middleware

# Source files
#VisualGDBAndroid: AutoUpdateSourcesInNextLine
LOCAL_SRC_FILES := ../CPUT/CPUTAnimation.cpp ../CPUT/CPUTAssetLibrary.cpp ../CPUT/CPUTAssetLibraryOGL.cpp ../CPUT/CPUTAssetSet.cpp ../CPUT/CPUTBufferOGL.cpp ../CPUT/CPUTButton.cpp ../CPUT/CPUTCamera.cpp ../CPUT/CPUTCheckbox.cpp ../CPUT/CPUTConfigBlock.cpp ../CPUT/CPUTControl.cpp ../CPUT/CPUTDropdown.cpp ../CPUT/CPUTFont.cpp ../CPUT/CPUTFrustum.cpp ../CPUT/CPUTGuiController.cpp ../CPUT/CPUTGuiControllerOGL.cpp ../CPUT/CPUTGUIElement.cpp ../CPUT/CPUTITTTaskMarker.cpp ../CPUT/CPUTLight.cpp ../CPUT/CPUTMaterial.cpp ../CPUT/CPUTMaterialEffect.cpp ../CPUT/CPUTMaterialEffectOGL.cpp ../CPUT/CPUTMesh.cpp ../CPUT/CPUTMeshOGL.cpp ../CPUT/CPUTModel.cpp ../CPUT/CPUTModelOGL.cpp ../CPUT/CPUTNullNode.cpp ../CPUT/CPUTOSServicesLinux.cpp ../CPUT/CPUTParser.cpp ../CPUT/CPUTPerfTaskMarker.cpp ../CPUT/CPUTRenderNode.cpp ../CPUT/CPUTRenderStateBlock.cpp ../CPUT/CPUTRenderStateBlockOGL.cpp ../CPUT/CPUTRenderTargetOGL.cpp ../CPUT/CPUTScene.cpp ../CPUT/CPUTShaderOGL.cpp ../CPUT/CPUTSlider.cpp ../CPUT/CPUTSprite.cpp ../CPUT/CPUTSpriteOGL.cpp ../CPUT/CPUTText.cpp ../CPUT/CPUTTexture.cpp ../CPUT/CPUTTextureOGL.cpp ../CPUT/CPUTTimerLinux.cpp ../CPUT/CPUTWindowAndroid.cpp ../CPUT/CPUT_OGL.cpp ../CPUT/CPUT_OGL_GLES.cpp ../middleware/libktx/checkheader.c ../middleware/libktx/errstr.c ../middleware/libktx/hashtable.c ../middleware/libktx/loader.c ../middleware/libktx/swap.c ../middleware/libktx/writer.c ../middleware/ndk_helper/gestureDetector.cpp ../middleware/ndk_helper/JNIHelper.cpp ../middleware/ndk_helper/vecmath.cpp ../middleware/stb/stb_image.c

# Build instructions
include $(BUILD_STATIC_LIBRARY)

# Project dependencies
$(call import-module, android/native_app_glue)
